default:
  image: ubuntu:bionic

stages:
  - ubuntu
  - centos
  - arch

bootstrap_ubuntu:
  stage: ubuntu
  script:
    - whoami
    - printenv
    - apt-get update; apt-get install -y sudo
    - ./bootstrap

bootstrap_centos7:
  image: centos:7
  stage: centos
  script:
    - whoami
    - printenv
    - ./bootstrap

bootstrap_arch:
  image: archlinux/base
  stage: arch
  script:
    - whoami
    - printenv
    - ./bootstrap
