default:
  image: ubuntu:bionic

stages:
  - arch
  - centos
  - ubuntu

bootstrap_ubuntu:
  stage: ubuntu
  script:
    - whoami
    - printenv
    - apt-get update; apt-get install -y sudo
    - ./bootstrap -y

bootstrap_centos7:
  image: centos:7
  stage: centos
  script:
    - whoami
    - printenv
    - yum -y update; yum install -y sudo
    - ./bootstrap -y

bootstrap_arch:
  image: archlinux/base
  stage: arch
  script:
    - whoami
    - printenv
    - cat ./xyne.pac >> /etc/pacman.conf
    - pacman -Sy
    - pacman -Su
    - pacman -S --noconfirm sudo powerpill bauerbill
    - ./bootstrap -y
